name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-test-github-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - name: Check out into sample-ms repo
        uses: actions/checkout@v3
          
      - run: export GRADLE_USER_HOME="$pwd/.gradle"
       
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      
      - name: Build Gradle and Unit Test
        run: |
          chmod +x gradlew
          ./gradlew clean build --write-locks
