name: gradle-build
on: [push]
jobs:
  gradle-build-Job:
    runs-on:
      - codebuild-test-github-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: gradle clean build --write-locks
              
