name: Hello World
on: [push]
jobs:
  Gradle-Build:
    runs-on:
      - codebuild-test-github-${{ github.run_id }}-${{ github.run_attempt }}
      - buildspec-override:true
    steps:
      - name: Build Gradle and Unit Test
        run: |
          gradlew clean build --write-locks
    
